[package]
name = "stepflow-openapi"
version = "0.1.0"
edition = "2021"
description = "Stepflow Tool System - OpenAPI Integration"
license = "MIT"
repository = "https://github.com/stepflow/stepflow-toolkit"
keywords = ["stepflow", "openapi", "swagger", "specification"]
categories = ["api-bindings", "development-tools"]

[dependencies]
stepflow-core = { path = "../stepflow-core" }
stepflow-database = { path = "../stepflow-database" }
stepflow-monitoring = { path = "../stepflow-monitoring" }

tokio = { workspace = true, features = ["sync"] }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
serde_yaml = "0.9"
urlencoding = "2.1"
base64 = "0.22"

# Tree-sitter dependencies with fixed versions
tree-sitter = "0.25"
tree-sitter-json = "0.24"
tree-sitter-yaml = "0.7.1"

# HTTP client dependencies
reqwest = { version = "0.12", features = ["json"] }
hyper = { version = "1.0", features = ["full"] }
hyper-util = "0.1"

[dev-dependencies]
tokio-test = "0.4"
axum = "0.7"
tower = "0.4"
hyper-util = "0.1"