[package]
name = "stepflow-system"
version = "0.1.0"
edition = "2021"
description = "Stepflow Tool System - System Integration"
license = "MIT"
repository = "https://github.com/stepflow/stepflow-toolkit"
keywords = ["stepflow", "system", "integration", "platform"]
categories = ["api-bindings", "development-tools"]

[dependencies]
stepflow-core = { path = "../stepflow-core" }
stepflow-database = { path = "../stepflow-database" }
stepflow-registry = { path = "../stepflow-registry" }
stepflow-executor = { path = "../stepflow-executor" }
stepflow-monitoring = { path = "../stepflow-monitoring" }

tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true } 