[package]
name = "stepflow-registry"
version = "0.1.0"
edition = "2021"
description = "Tool registry for Stepflow Tool System"
license = "MIT"
repository = "https://github.com/stepflow/stepflow-toolkit"

[dependencies]
stepflow-core = { path = "../stepflow-core" }
stepflow-database = { path = "../stepflow-database" }

# 异步支持
tokio = { workspace = true }
async-trait = { workspace = true }

# 序列化
serde = { workspace = true }
serde_json = { workspace = true }

# 错误处理
thiserror = { workspace = true }

# 时间
chrono = { workspace = true }

# UUID
uuid = { workspace = true }

# 日志
tracing = { workspace = true }

# 其他
futures = { workspace = true }

# 缓存
lru = "0.12"

# 正则表达式
regex = "1.10"

# 语义化版本
semver = "1.0"

[dev-dependencies]
tokio-test = "0.4" 