[package]
name = "stepflow-core"
version = "0.1.0"
edition = "2021"
description = "Core interfaces and types for Stepflow Tool System"
license = "MIT"
repository = "https://github.com/stepflow/stepflow-toolkit"

[dependencies]
# 异步支持
tokio = { workspace = true }
async-trait = { workspace = true }

# 序列化
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# 错误处理
thiserror = { workspace = true }

# 时间
chrono = { workspace = true, features = ["serde"] }

# UUID
uuid = { workspace = true }

# 日志
tracing = { workspace = true }

# 系统
num_cpus = { workspace = true }

# 其他
futures = { workspace = true }
validator = { version = "0.16", features = ["derive"] }

[dev-dependencies]
tokio-test = "0.4" 