[package]
name = "stepflow-executor"
version = "0.1.0"
edition = "2021"
description = "Stepflow Tool System - Execution Engine"
license = "MIT"
repository = "https://github.com/stepflow/stepflow-toolkit"
keywords = ["stepflow", "executor", "workflow", "execution"]
categories = ["api-bindings", "development-tools"]

[dependencies]
stepflow-core = { path = "../stepflow-core" }
stepflow-database = { path = "../stepflow-database" }
stepflow-registry = { path = "../stepflow-registry" }
stepflow-monitoring = { path = "../stepflow-monitoring" }

tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
dashmap = "5.0"
parking_lot = "0.12"
crossbeam-channel = "0.5" 