[package]
name = "stepflow-embedding"
version = "0.1.0"
edition = "2021"
description = "Stepflow Tool System - Embedding Engine"
license = "MIT"
repository = "https://github.com/stepflow/stepflow-toolkit"
keywords = ["stepflow", "embedding", "vector", "similarity"]
categories = ["api-bindings", "development-tools"]

[dependencies]
stepflow-core = { path = "../stepflow-core" }
stepflow-database = { path = "../stepflow-database" }
stepflow-monitoring = { path = "../stepflow-monitoring" }

tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true } 